theme: jekyll-theme-minimal
logo: /assets/img/WordCloud.png

google_analytics: G-Q92Z71T44M

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-Q92Z71T44M        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
